integration:
  - changed-files:
      - any-glob-to-any-file: "custom_components/**"

tests:
  - changed-files:
      - any-glob-to-any-file: "tests/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "docs/**"
