sonar.organization=brianegge
sonar.projectKey=brianegge_homeassistant-obs-studio
sonar.sources=custom_components/obs_websocket
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
